apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: syncer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get 
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  verbs:  
  - list  
  - get 
