apiVersion: v1
kind: Service
metadata:
  name: ng-plus-syncer-hs
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ng-plus-syncer
  sessionAffinity: None
  type: ClusterIP
