apiVersion: v1
kind: Service
metadata:
  name: ng-plus-syncer
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ng-plus-syncer
  sessionAffinity: None
  type: ClusterIP
status: {}
